### ISSUE TITLE
already exists

### ISSUE THREAD

**Issue by jonschlinkert** [sindresorhus/modify-keys#1]
https://github.com/jonschlinkert/rename-keys

**Comment by sindresorhus** [comment]
https://www.npmjs.com/search?q=modify+keys

Yeah, I guess it's pretty close, but looking at yours it's different in some ways. Yours falls back if no value if returned, mine requires a value to be returned. Mine also exposes the value and is more performant.

Lets stop this silliness though. I could open a bunch of issues on your repos too.

https://github.com/jonschlinkert/arr-diff --> https://github.com/sindresorhus/array-differ

**Comment by jonschlinkert** [comment]
> Lets stop this silliness though. I could open a bunch of issues on your repos too.

Wow, okay. You just opened some on mine in the last couple of days. Are you saying that you don't want to know when you create libraries that are duplicates of mine? But you do want me to create issues on my projects to let me know when I create a project that is kind of similar to yours?  

> Mine also exposes the value 

Would have been nice to get a pr for `var val = obj[key]`. Or a feature request.

> and is more performant.

You've said that before on other repos. In what usage scenario? As with those, my lib covers more usage scenarios, and I just did a quick benchmark:

``` js
  modify-keys.js x 861,401 ops/sec ±0.97% (90 runs sampled)
  rename-keys.js x 997,011 ops/sec ±0.61% (96 runs sampled)
```

I'm sure there would be wildly different results for different benchmarks, but who cares? the point is, stopping saying that. It's naive, and usually wrong.
